CREATE TABLE IF NOT EXISTS payments (
id SERIAL PRIMARY KEY,
payment_method CHARACTER VARYING(100) NOT NULL,
paid_amount NUMERIC NOT NULL,
created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
payer_name CHARACTER VARYING(255),
user_email CHARACTER VARYING(255) NOT NULL
);