CREATE TABLE IF NOT EXISTS orders (
id SERIAL PRIMARY KEY,
order_id CHARACTER VARYING(255) NOT NULL,
total_amount NUMERIC NOT NULL,
client_name CHARACTER VARYING(100),
created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT uq_order_id UNIQUE (order_id)
);

CREATE TABLE IF NOT EXISTS ordered_items (
id SERIAL PRIMARY KEY,
product_id CHARACTER VARYING(100),
price NUMERIC NOT NULL,
quantity INTEGER DEFAULT 0,
created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
order_id BIGINT NOT NULL,
CONSTRAINT fk_items_order_id FOREIGN KEY (order_id) REFERENCES orders (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
);