spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            default-filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: user
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**, /api/v1/admin/**
          filters:
            - TokenValidationFilter
        - id: user_swagger
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/aggregate/user-service/v3/api-docs
          filters:
            - SetPath=/api-docs
        - id: product
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
          filters:
            - TokenValidationFilter
        - id: product_swagger
          uri: lb:http://PRODUCT-SERVICE
          predicates:
            - Path=/aggregate/product-service/v3/api-docs
          filters:
            - SetPath=/api-docs
        - id: order
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - TokenValidationFilter
        - id: order_swagger
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/aggregate/order-service/v3/api-docs
          filters:
            - SetPath=/api-docs
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      gatewayCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
  timelimiter:
    instances:
      gatewayTimeLimiter:
        timeout-duration: 3s
  retry:
    instances:
      gatewayRetry:
        max-attempts: 3
        wait-duration: 2s
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /aggregate/user-service/v3/api-docs
        name: User Service
      - url: /aggregate/product-service/v3/api-docs
        name: Product Service
      - url: /aggregate/order-service/v3/api-docs
        name: Order Service
  api-docs:
    path: /api-docs
server:
  port: 9000
client:
  user:
    url: http://localhost:8001
