spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
server:
  port: 9000
