spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orders
    username: zel
    password: 123
    jpa:
      open-in-view: false
      database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
      show-sql: true
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          globally_quoted_identifiers: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: zel
    password: 123
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      orderCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
  timelimiter:
    instances:
      orderTimeLimiter:
        timeout-duration: 3s
  retry:
    instances:
      orderRetry:
        max-attempts: 3
        wait-duration: 2s
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
client:
  inventory:
    url: http://localhost:8004
  product:
    url: http://localhost:8002
  user:
    url: http://localhost:8001
  payment:
    url: http://localhost:8005
server:
  port: 8003