spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/products
    username: zel
    password: 123
    jpa:
      open-in-view: false
      database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
      show-sql: true
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          globally_quoted_identifiers: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: zel
    password: 123
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
client:
  inventory:
    url: http://localhost:8004
  user:
    url: http://localhost:8001

server:
  port: 8002