CREATE TABLE IF NOT EXISTS categories (
id SERIAL PRIMARY KEY,
type CHARACTER VARYING(100) NOT NULL,
CONSTRAINT uq_products_type UNIQUE (type)
);

CREATE TABLE IF NOT EXISTS products (
id SERIAL PRIMARY KEY,
product_id CHARACTER VARYING(255) NOT NULL,
name CHARACTER VARYING(100) NOT NULL,
description CHARACTER VARYING(255),
price NUMERIC NOT NULL,
quantity INTEGER DEFAULT 0,
owner_id CHARACTER VARYING(100),
category CHARACTER VARYING(50),
CONSTRAINT uq_product_id UNIQUE (product_id),
CONSTRAINT fk_products_owner_id FOREIGN KEY (category) REFERENCES categories (type) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
);