CREATE TABLE IF NOT EXISTS locations(
id SERIAL PRIMARY KEY,
reference_id CHARACTER VARYING(255),
country CHARACTER VARYING(50),
city CHARACTER VARYING(50),
street CHARACTER VARYING(100),
zip_code CHARACTER VARYING(50),
user_id BIGINT NOT NULL,
created_by BIGINT NOT NULL,
updated_by BIGINT NOT NULL,
created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT uq_locations_user_id UNIQUE (user_id),
CONSTRAINT fk_locations_user_id FOREIGN KEY (user_id) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_locations_created_by FOREIGN KEY (created_by) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_locations_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
);